### ISSUE TITLE
ska 1.0 now in homebrew

### ISSUE THREAD

**Issue by tseemann** [simonrharris/SKA#14]
🎉 New formula ska in Brewsci/bio for Linux and macOS!
ℹ️ Split Kmer Analysis toolkit
🍺 brew install brewsci/bio/ska
🏡 https://github.com/simonrharris/SKA/releases
🔬 https://github.com/brewsci/homebrew-bio
🐧 http://linuxbrew.sh #bioinformatics

**Comment by simonrharris** [comment]
Thanks for this Torsten! Added to the installation instructions.
