### ISSUE TITLE
Order of `type` columns

### ISSUE THREAD

**Issue by tseemann** [simonrharris/SKA#17]
Currently 
`Sample  adk     atpA    ddl     gdh     gyd     pstS    purK    ST`

Any chance making it compatible with `mlst`?
`Sample  ST  adk     atpA    ddl     gdh     gyd     pstS    purK`

This has the advantage that no matter how many alleles in the scheme, the ST  will be consistent.

But I understand that ST is not compulsory, and that this could be used for assaying all sorts of amplicons such as AMR genes.

**Comment by simonrharris** [comment]
I can do that. TBH the order I chose was a little arbitrary.

**Comment by simonrharris** [comment]
The order has been changed in commit 56babcbfe0cc83ed83bd9bb8e2ef927ef08d6632
