### ISSUE TITLE
Add counts of different alleles at each site in each sample in a reference free alignment

### ISSUE THREAD

**Issue by gtonkinhill** [simonrharris/SKA#9]

**Comment by simonrharris** [comment]
SKA doesn't have that information at that stage, but I could output it from ska fastq and provide a way to look up allele frequencies based on a set of split kmers. Would that work?

**Comment by simonrharris** [comment]
I've added the option to output allele counts during ska fastq and also ska humanise to output kmers in a human readable format (with the middle bases of each sample). You should be able to use the first column from that to find your allele freqeuncies in the allele count files.
